INSERT INTO artists (name, bio, genre) VALUES 
('Green Lung', 'Influenced by the folklore, myths and legends of Britain', 'Metal' ), 
('MUNA', 'An American indie pop band', 'Indie Pop' ), 
('Paramore', 'Three-time Grammy-winning band from Tennessee', 'Indie Pop' ),
('Blood Orange', 'AKA Dev Hynes based in NYC', 'Alternative Indie'),
('Christine and the Queens', 'French pop artist with theatrical flair', 'Pop'),
('Black Sabbath', 'Pioneers of heavy metal since the 1970s', 'Metal'),
('Judas Priest', 'A defining band in the evolution of metal', 'Metal'),
('Turnstile', 'Energetic hardcore punk', 'Hardcore Punk'),
('Chappell Roan', 'Emerging pop artist', 'Pop'),
('Charli XCX', 'Innovative pop artist pushing genre boundaries', 'Pop'),
('Periphery', 'Progressive metal band', 'Progressive Metal'),
('Little Simz', 'British rapper', 'Hip Hop'),
('NoSo', 'Introspective indie pop artist', 'Indie Pop'),
('Electric Wizard', 'Classic doom metal band', 'Doom Metal'),
('boygenius', 'Indie rock supergroup', 'Indie Rock'),
('Kaytranada', 'Genre-blending electronic music producer', 'Electronic'),
('Cathedral', 'British doom metal', 'Doom Metal'),
('The Cure', 'Influential gothic rock band', 'Gothic Rock'),
('Kate Bush', 'Art pop icon', 'Art Pop');

INSERT INTO albums (title, release_date, genre, artist_id) VALUES
('This is Why', '2023-02-01', 'Alternative', (SELECT id FROM artists WHERE name = 'Paramore')),
('This Heathen Land', '2023-11-01', 'Metal', (SELECT id FROM artists WHERE name = 'Green Lung')),
('Woodland Rites', '2019-03-01', 'Metal', (SELECT id FROM artists WHERE name = 'Green Lung')),
('Cupid Deluxe', '2013-11-01', 'Alternative Indie', (SELECT id FROM artists WHERE name = 'Blood Orange')),
('Chris', '2018-09-01', 'Pop', (SELECT id FROM artists WHERE name = 'Christine and the Queens')),
('Black Sabbath', '1970-02-01', 'Metal', (SELECT id FROM artists WHERE name = 'Black Sabbath')),
('Paranoid', '1970-09-01', 'Metal', (SELECT id FROM artists WHERE name = 'Black Sabbath')),
('British Steel', '1980-04-01', 'Metal', (SELECT id FROM artists WHERE name = 'Judas Priest')),
('Time & Space', '2018-02-01', 'Hardcore Punk', (SELECT id FROM artists WHERE name = 'Turnstile')),
('The Rise and Fall of a Midwest Princess', '2023-09-01', 'Pop', (SELECT id FROM artists WHERE name = 'Chappell Roan')),
('Brat', '2024-06-01', 'Pop', (SELECT id FROM artists WHERE name = 'Charli XCX')),
('Periphery', '2010-04-01', 'Progressive Metal', (SELECT id FROM artists WHERE name = 'Periphery')),
('MUNA', '2024-06-01', 'Indie Pop', (SELECT id FROM artists WHERE name = 'MUNA')),
('Sometimes I Might Be Introvert', '2021-09-01', 'Hip Hop', (SELECT id FROM artists WHERE name = 'Little Simz')),
('Stay Proud of Me', '2022-07-01', 'Indie Pop', (SELECT id FROM artists WHERE name = 'NoSo')),
('Painkiller', '1990-09-01', 'Metal', (SELECT id FROM artists WHERE name = 'Judas Priest')),
('Master of Reality', '1971-07-01', 'Metal', (SELECT id FROM artists WHERE name = 'Black Sabbath')),
('Sabbath Bloody Sabbath', '1973-12-01', 'Metal', (SELECT id FROM artists WHERE name = 'Black Sabbath')),
('Never Say Die', '1978-09-01', 'Metal', (SELECT id FROM artists WHERE name = 'Black Sabbath')),
('Witchcult Today', '2007-11-01', 'Doom Metal', (SELECT id FROM artists WHERE name = 'Electric Wizard')),
('ABOUT U', '2017-02-01', 'Indie Pop', (SELECT id FROM artists WHERE name = 'MUNA')),
('boygenius', '2018-10-01', 'Indie Rock', (SELECT id FROM artists WHERE name = 'boygenius')),
('BUBBA', '2019-12-01', 'Electronic', (SELECT id FROM artists WHERE name = 'Kaytranada')),
('GLOW ON', '2021-08-01', 'Hardcore Punk', (SELECT id FROM artists WHERE name = 'Turnstile')),
('The Carnival Bizarre', '1995-09-01', 'Doom Metal', (SELECT id FROM artists WHERE name = 'Cathedral')),
('Disintegration', '1989-05-01', 'Gothic Rock', (SELECT id FROM artists WHERE name = 'The Cure')),
('Hounds of Love', '1985-09-01', 'Art Pop', (SELECT id FROM artists WHERE name = 'Kate Bush'));


INSERT INTO album_artists (album_id, artist_id) VALUES 
((SELECT id FROM albums WHERE title = 'This is Why'), (SELECT id FROM artists WHERE name = 'Paramore')),
((SELECT id FROM albums WHERE title = 'This Heathen Land'), (SELECT id FROM artists WHERE name = 'Green Lung')),
((SELECT id FROM albums WHERE title = 'Woodland Rites'), (SELECT id FROM artists WHERE name = 'Green Lung')),
((SELECT id FROM albums WHERE title = 'Cupid Deluxe'), (SELECT id FROM artists WHERE name = 'Blood Orange')),
((SELECT id FROM albums WHERE title = 'Chris'), (SELECT id FROM artists WHERE name = 'Christine and the Queens')),
((SELECT id FROM albums WHERE title = 'Black Sabbath'), (SELECT id FROM artists WHERE name = 'Black Sabbath')),
((SELECT id FROM albums WHERE title = 'Paranoid'), (SELECT id FROM artists WHERE name = 'Black Sabbath')),
((SELECT id FROM albums WHERE title = 'British Steel'), (SELECT id FROM artists WHERE name = 'Judas Priest')),
((SELECT id FROM albums WHERE title = 'Time & Space'), (SELECT id FROM artists WHERE name = 'Turnstile')),
((SELECT id FROM albums WHERE title = 'The Rise and Fall of a Midwest Princess'), (SELECT id FROM artists WHERE name = 'Chappell Roan')),
((SELECT id FROM albums WHERE title = 'Brat'), (SELECT id FROM artists WHERE name = 'Charli XCX')),
((SELECT id FROM albums WHERE title = 'Periphery'), (SELECT id FROM artists WHERE name = 'Periphery')),
((SELECT id FROM albums WHERE title = 'MUNA'), (SELECT id FROM artists WHERE name = 'MUNA')),
((SELECT id FROM albums WHERE title = 'Sometimes I Might Be Introvert'), (SELECT id FROM artists WHERE name = 'Little Simz')),
((SELECT id FROM albums WHERE title = 'Stay Proud of Me'), (SELECT id FROM artists WHERE name = 'NoSo')),
((SELECT id FROM albums WHERE title = 'Painkiller'), (SELECT id FROM artists WHERE name = 'Judas Priest')),
((SELECT id FROM albums WHERE title = 'Master of Reality'), (SELECT id FROM artists WHERE name = 'Black Sabbath')),
((SELECT id FROM albums WHERE title = 'Sabbath Bloody Sabbath'), (SELECT id FROM artists WHERE name = 'Black Sabbath')),
((SELECT id FROM albums WHERE title = 'Never Say Die'), (SELECT id FROM artists WHERE name = 'Black Sabbath')),
((SELECT id FROM albums WHERE title = 'Witchcult Today'), (SELECT id FROM artists WHERE name = 'Electric Wizard')),
((SELECT id FROM albums WHERE title = 'ABOUT U'), (SELECT id FROM artists WHERE name = 'MUNA')),
((SELECT id FROM albums WHERE title = 'boygenius'), (SELECT id FROM artists WHERE name = 'boygenius')),
((SELECT id FROM albums WHERE title = 'BUBBA'), (SELECT id FROM artists WHERE name = 'Kaytranada')),
((SELECT id FROM albums WHERE title = 'GLOW ON'), (SELECT id FROM artists WHERE name = 'Turnstile')),
((SELECT id FROM albums WHERE title = 'The Carnival Bizarre'), (SELECT id FROM artists WHERE name = 'Cathedral')),
((SELECT id FROM albums WHERE title = 'Disintegration'), (SELECT id FROM artists WHERE name = 'The Cure')),
((SELECT id FROM albums WHERE title = 'Hounds of Love'), (SELECT id FROM artists WHERE name = 'Kate Bush'));
